# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b096c75cf03adad08857e83e198db238aa0670ef2e71e24a2680e49a314f15f5f25fa815139b5aa3ce09c62c0630d8c4e43e0e30404ae7a7c682262942bebd22

test:
  secret_key_base: 13a44e114d74527b91202796ecd08690824dfe98a033f41c459f8565a1e80e1166174fcc9e98db39e6a459ddd446267d1675e5eab719e3c6d99b7c3d28a20c95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
